### ISSUE TITLE
<FEAT-REQUEST> QUICK SORT 

### ISSUE THREAD

**Issue by manikanta-parameshwarappa** [itsjohnty/Hacktoberfest#5]
@itsjohnty I want to add a java code /(algorithm ) of the BEST SORTING ALGORITHM QUICK SORT .

**Comment by itsjohnty** [comment]
Sure you can make a Pull request

**Comment by manikanta-parameshwarappa** [comment]
iam beginner to open source and got to know about hacktober fest 2023 , i wanted to explore !
THANKS for the opportunity ! @itsjohnty 
<html>
<img src="https://media.tenor.com/ZwiJdgs2un0AAAAC/thank-you-tanjiro.gif">
</html>

**Comment by manikanta-parameshwarappa** [comment]
Iam closing This Issue !
As it is Solved !!
<html>
<img src="https://usagif.com/wp-content/uploads/gify/naruto-happy-hooray-usagifdotcom-title.gif">
</html>
